import type { KonsonantenhaufungWord, KonsonantenhaufungQuizQuestion } from '../types';

export const konsonantenhaufungen: KonsonantenhaufungWord[] = [
  { group: 'bl', word: 'Blase', syllables: 'Bla-se', translation: 'bulle, ampoule' },
  { group: 'bl', word: 'Blatt', syllables: 'Blatt', translation: 'feuille' },
  { group: 'bl', word: 'blau', syllables: 'blau', translation: 'bleu' },
  { group: 'dr', word: 'drei', syllables: 'drei', translation: 'trois' },
  { group: 'dr', word: 'Droge', syllables: 'Dro-ge', translation: 'drogue' },
  { group: 'dr', word: 'drehen', syllables: 'dre-hen', translation: 'tourner' },
  { group: 'fl', word: 'Flasche', syllables: 'Fla-sche', translation: 'bouteille' },
  { group: 'fl', word: 'Floh', syllables: 'Floh', translation: 'puce' },
  { group: 'fl', word: 'flau', syllables: 'flau', translation: 'nauséeux' },
  { group: 'fr', word: 'froh', syllables: 'froh', translation: 'content' },
  { group: 'fr', word: 'fressen', syllables: 'fres-sen', translation: 'manger (animaux)' },
  { group: 'fr', word: 'frisch', syllables: 'frisch', translation: 'frais' },
  { group: 'gl', word: 'Gleis', syllables: 'Gleis', translation: 'voie ferrée' },
  { group: 'gl', word: 'glatt', syllables: 'glatt', translation: 'lisse' },
  { group: 'gl', word: 'Glas', syllables: 'Glas', translation: 'verre' },
  { group: 'gn', word: 'Gnu', syllables: 'Gnu', translation: 'gnou' },
  { group: 'gn', word: 'Gnade', syllables: 'Gna-de', translation: 'grâce, pitié' },
  { group: 'gn', word: 'Gnom', syllables: 'Gnom', translation: 'gnome' },
  { group: 'gr', word: 'grau', syllables: 'grau', translation: 'gris' },
  { group: 'gr', word: 'Gras', syllables: 'Gras', translation: 'herbe' },
  { group: 'gr', word: 'groß', syllables: 'groß', translation: 'grand' },
  { group: 'kl', word: 'klein', syllables: 'klein', translation: 'petit' },
  { group: 'kl', word: 'Klinik', syllables: 'Kli-nik', translation: 'clinique' },
  { group: 'kl', word: 'Klima', syllables: 'Kli-ma', translation: 'climat' },
  { group: 'kr', word: 'krank', syllables: 'krank', translation: 'malade' },
  { group: 'kr', word: 'Kreis', syllables: 'Kreis', translation: 'cercle' },
  { group: 'kr', word: 'Krake', syllables: 'Kra-ke', translation: 'pieuvre' },
  { group: 'pfl', word: 'Pflanze', syllables: 'Pflan-ze', translation: 'plante' },
  { group: 'pfl', word: 'Pflege', syllables: 'Pfle-ge', translation: 'soin' },
  { group: 'pfl', word: 'Pflaume', syllables: 'Pflau-me', translation: 'prune' },
  { group: 'pr', word: 'prall', syllables: 'prall', translation: 'tendu, rebondi' },
  { group: 'pr', word: 'Preis', syllables: 'Preis', translation: 'prix' },
  { group: 'pr', word: 'Prost', syllables: 'Prost', translation: 'santé !' },
  { group: 'schl', word: 'schlank', syllables: 'schlank', translation: 'mince' },
  { group: 'schl', word: 'Schloss', syllables: 'Schloss', translation: 'château' },
  { group: 'schl', word: 'schlau', syllables: 'schlau', translation: 'malin' },
  { group: 'schm', word: 'schmal', syllables: 'schmal', translation: 'étroit' },
  { group: 'schm', word: 'Schmalz', syllables: 'Schmalz', translation: 'saindoux' },
  { group: 'schm', word: 'schmelzen', syllables: 'schmel-zen', translation: 'fondre' },
  { group: 'schn', word: 'Schnee', syllables: 'Schnee', translation: 'neige' },
  { group: 'schn', word: 'schnell', syllables: 'schnell', translation: 'rapide' },
  { group: 'schn', word: 'Schneide', syllables: 'Schnei-de', translation: 'lame' },
  { group: 'schr', word: 'schreien', syllables: 'schrei-en', translation: 'crier' },
  { group: 'schr', word: 'Schreck', syllables: 'Schreck', translation: 'frayeur' },
  { group: 'schr', word: 'Schrot', syllables: 'Schrot', translation: 'grenaille' },
  { group: 'schw', word: 'schwarz', syllables: 'schwarz', translation: 'noir' },
  { group: 'schw', word: 'schwer', syllables: 'schwer', translation: 'lourd, difficile' },
  { group: 'schw', word: 'schwach', syllables: 'schwach', translation: 'faible' },
  { group: 'spr', word: 'Sprache', syllables: 'Spra-che', translation: 'langue' },
  { group: 'spr', word: 'springen', syllables: 'sprin-gen', translation: 'sauter' },
  { group: 'spr', word: 'spritzen', syllables: 'sprit-zen', translation: 'gicler, injecter' },
  { group: 'str', word: 'Stroh', syllables: 'Stroh', translation: 'paille' },
  { group: 'str', word: 'Straße', syllables: 'Stra-ße', translation: 'rue' },
  { group: 'str', word: 'Strand', syllables: 'Strand', translation: 'plage' },
  { group: 'tr', word: 'Tran', syllables: 'Tran', translation: 'huile de poisson' },
  { group: 'tr', word: 'trocken', syllables: 'tro-cken', translation: 'sec' },
  { group: 'tr', word: 'Traum', syllables: 'Traum', translation: 'rêve' },
  { group: 'zw', word: 'zwischen', syllables: 'zwi-schen', translation: 'entre' },
  { group: 'zw', word: 'zwölf', syllables: 'zwölf', translation: 'douze' },
  { group: 'zw', word: 'Zwinger', syllables: 'Zwin-ger', translation: 'chenil' },
];

export const internalKonsonantenhaufungen: KonsonantenhaufungWord[] = [
  { group: 'cht', word: 'Licht', syllables: 'Licht', translation: 'lumière' },
  { group: 'cht', word: 'macht', syllables: 'macht', translation: 'fait' },
  { group: 'ckt', word: 'nackt', syllables: 'nackt', translation: 'nu' },
  { group: 'ckt', word: 'zuckt', syllables: 'zuckt', translation: 'tressaille' },
  { group: 'ckt', word: 'druckt', syllables: 'druckt', translation: 'imprime' },
  { group: 'dt', word: 'Stadt', syllables: 'Stadt', translation: 'ville' },
  { group: 'dt', word: 'Schmidt', syllables: 'Schmidt', translation: '(nom)' },
  { group: 'dt', word: 'verwandt', syllables: 'ver-wandt', translation: 'apparenté' },
  { group: 'ft', word: 'Haft', syllables: 'Haft', translation: 'détention' },
  { group: 'ft', word: 'Saft', syllables: 'Saft', translation: 'jus' },
  { group: 'ft', word: 'Heft', syllables: 'Heft', translation: 'cahier' },
  { group: 'ng', word: 'Sprung', syllables: 'Sprung', translation: 'saut' },
  { group: 'ng', word: 'Zeitung', syllables: 'Zei-tung', translation: 'journal' },
  { group: 'ng', word: 'bang', syllables: 'bang', translation: 'effrayé' },
  { group: 'ngt', word: 'springt', syllables: 'springt', translation: 'saute' },
  { group: 'ngt', word: 'singt', syllables: 'singt', translation: 'chante' },
  { group: 'ngt', word: 'langt', syllables: 'langt', translation: 'suffit' },
  { group: 'nkt', word: 'trinkt', syllables: 'trinkt', translation: 'boit' },
  { group: 'nkt', word: 'sinkt', syllables: 'sinkt', translation: 'coule' },
  { group: 'nkt', word: 'lenkt', syllables: 'lenkt', translation: 'dirige' },
  { group: 'nkt', word: 'Punkt', syllables: 'Punkt', translation: 'point' },
  { group: 'nkt', word: 'denkt', syllables: 'denkt', translation: 'pense' },
  { group: 'kt', word: 'Sekt', syllables: 'Sekt', translation: 'vin mousseux' },
  { group: 'nd', word: 'Rand', syllables: 'Rand', translation: 'bord' },
  { group: 'nd', word: 'Sand', syllables: 'Sand', translation: 'sable' },
  { group: 'nd', word: 'und', syllables: 'und', translation: 'et' },
  { group: 'nz', word: 'ganz', syllables: 'ganz', translation: 'entier' },
  { group: 'nz', word: 'Tanz', syllables: 'Tanz', translation: 'danse' },
  { group: 'nz', word: 'Heinz', syllables: 'Heinz', translation: '(prénom)' },
  { group: 'ld', word: 'bald', syllables: 'bald', translation: 'bientôt' },
  { group: 'ld', word: 'Geld', syllables: 'Geld', translation: 'argent' },
  { group: 'ld', word: 'Gold', syllables: 'Gold', translation: 'or' },
  { group: 'lf', word: 'hilf', syllables: 'hilf', translation: 'aide !' },
  { group: 'lf', word: 'elf', syllables: 'elf', translation: 'onze' },
  { group: 'lf', word: 'Golf', syllables: 'Golf', translation: 'golf' },
  { group: 'lk', word: 'welk', syllables: 'welk', translation: 'fané' },
  { group: 'lk', word: 'Kalk', syllables: 'Kalk', translation: 'chaux' },
  { group: 'lk', word: 'Volk', syllables: 'Volk', translation: 'peuple' },
  { group: 'lm', word: 'Helm', syllables: 'Helm', translation: 'casque' },
  { group: 'lm', word: 'Halm', syllables: 'Halm', translation: 'brin' },
  { group: 'lm', word: 'Film', syllables: 'Film', translation: 'film' },
  { group: 'ln', word: 'regeln', syllables: 're-geln', translation: 'régler' },
  { group: 'ln', word: 'Nudeln', syllables: 'Nu-deln', translation: 'pâtes' },
  { group: 'ln', word: 'segeln', syllables: 'se-geln', translation: 'faire de la voile' },
  { group: 'ls', word: 'als', syllables: 'als', translation: 'que, quand' },
  { group: 'ls', word: 'teils', syllables: 'teils', translation: 'en partie' },
  { group: 'ls', word: 'falls', syllables: 'falls', translation: 'au cas où' },
  { group: 'lz', word: 'Holz', syllables: 'Holz', translation: 'bois' },
  { group: 'lz', word: 'Filz', syllables: 'Filz', translation: 'feutre' },
  { group: 'lz', word: 'Salz', syllables: 'Salz', translation: 'sel' },
  { group: 'mt', word: 'gesamt', syllables: 'ge-samt', translation: 'total' },
  { group: 'mt', word: 'Amt', syllables: 'Amt', translation: 'bureau' },
  { group: 'mt', word: 'Samt', syllables: 'Samt', translation: 'velours' },
  { group: 'ns', word: 'ins', syllables: 'ins', translation: 'dans le' },
  { group: 'ns', word: 'morgens', syllables: 'mor-gens', translation: 'le matin' },
  { group: 'ns', word: 'Gans', syllables: 'Gans', translation: 'oie' },
  { group: 'nst', word: 'einst', syllables: 'einst', translation: 'autrefois' },
  { group: 'nst', word: 'sonst', syllables: 'sonst', translation: 'sinon' },
  { group: 'nst', word: 'ernst', syllables: 'ernst', translation: 'sérieux' },
  { group: 'rd', word: 'Mord', syllables: 'Mord', translation: 'meurtre' },
  { group: 'rd', word: 'Ford', syllables: 'Ford', translation: '(marque)' },
  { group: 'rd', word: 'Herd', syllables: 'Herd', translation: 'cuisinière' },
  { group: 'rf', word: 'Wurf', syllables: 'Wurf', translation: 'lancer' },
  { group: 'rf', word: 'Dorf', syllables: 'Dorf', translation: 'village' },
  { group: 'rf', word: 'scharf', syllables: 'scharf', translation: 'piquant' },
  { group: 'rk', word: 'Werk', syllables: 'Werk', translation: 'usine, œuvre' },
  { group: 'rk', word: 'stark', syllables: 'stark', translation: 'fort' },
  { group: 'rk', word: 'Mark', syllables: 'Mark', translation: '(monnaie)' },
  { group: 'rkt', word: 'wirkt', syllables: 'wirkt', translation: 'agit, a l\'air' },
  { group: 'rkt', word: 'Markt', syllables: 'Markt', translation: 'marché' },
  { group: 'rkt', word: 'merkt', syllables: 'merkt', translation: 'remarque' },
  { group: 'rm', word: 'Wurm', syllables: 'Wurm', translation: 'ver' },
  { group: 'rm', word: 'Arm', syllables: 'Arm', translation: 'bras' },
  { group: 'rm', word: 'Form', syllables: 'Form', translation: 'forme' },
  { group: 'rn', word: 'Garn', syllables: 'Garn', translation: 'fil' },
  { group: 'rn', word: 'fern', syllables: 'fern', translation: 'lointain' },
  { group: 'rn', word: 'Zorn', syllables: 'Zorn', translation: 'colère' },
  { group: 'rt', word: 'Hort', syllables: 'Hort', translation: 'garderie' },
  { group: 'rt', word: 'Albert', syllables: 'Al-bert', translation: '(prénom)' },
  { group: 'rt', word: 'Geburt', syllables: 'Ge-burt', translation: 'naissance' },
  { group: 'rz', word: 'Herz', syllables: 'Herz', translation: 'cœur' },
  { group: 'rz', word: 'Harz', syllables: 'Harz', translation: 'résine' },
  { group: 'rz', word: 'kurz', syllables: 'kurz', translation: 'court' },
  { group: 'tzt', word: 'jetzt', syllables: 'jetzt', translation: 'maintenant' },
  { group: 'tzt', word: 'zuletzt', syllables: 'zu-letzt', translation: 'en dernier' },
  { group: 'tzt', word: 'nutzt', syllables: 'nutzt', translation: 'utilise' },
];


export const konsonantenhaufungenQuiz: KonsonantenhaufungQuizQuestion[] = [
    {
      question: 'Quel groupe de consonnes entend-on au début du mot "Straße" ?',
      options: ['str', 'schr', 'spr'],
      answer: 'str',
      explanation: 'Richtig ! Le mot commence par [ʃtʁ], donc "str".'
    },
    {
      question: 'Quel mot commence par le son [p͡fl] ?',
      options: ['Flasche', 'Pflanze', 'flau'],
      answer: 'Pflanze',
      explanation: 'Parfait ! "Pflanze" est un excellent exemple de ce groupe de consonnes.'
    },
    {
      question: 'Le mot "schwer" commence par le groupe de consonnes...',
      options: ['schw', 'sch', 'sp'],
      answer: 'schw',
      explanation: 'Très bien ! On entend bien le son [ʃv], qui correspond à "schw".'
    },
    {
      question: 'Vrai ou Faux : Le mot "Klinik" commence par le même groupe de consonnes que "klein".',
      options: ['Vrai', 'Faux'],
      answer: 'Vrai',
      explanation: 'Exactement ! Les deux mots commencent par le groupe "kl" [kl].'
    }
  ];